name: Docker Image CI

on:
  push:
    branches: [ radikrahl-patch-2 ]
  pull_request:
    branches: [ radikrahl-patch-2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:radikrahl-patch-2
